### ISSUE TITLE
Add `ChebTools`

### ISSUE THREAD

**Issue by dhirschfeld** [energy-quants/quantdev#52]
* https://github.com/usnistgov/ChebTools

**Comment by dhirschfeld** [comment]
* https://www.chebfun.org/examples/approx/Noisy.html
* https://www.chebfun.org/examples/approx/NoisyNonsmooth.html

**Comment by dhirschfeld** [comment]
```yaml
{% set name = "ChebTools" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ChebTools-{{ version }}.tar.gz
  sha256: c5210a08fda8fc93054dd800f45b7a6e948f52c0d5c03e105e7acd52de1bda00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=42
    - wheel
    - scikit-build
    - cmake >=3.17
    - ninja
    - pip
  run:
    - python

test:
  imports:
    - ChebTools
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Tools for working with Chebyshev expansion
  license: GPL-2.0 AND Unlicense AND MIT AND LGPL-2.1 AND BSD-3-Clause AND GPL-3.0 AND Apache-2.0 AND BSD-2-Clause AND MPL-2.0
  license_file:
    - LICENSE
    - externals/nanobind/LICENSE
    - externals/nanobind/ext/robin_map/LICENSE
    - externals/pybind11/LICENSE
    - externals/Eigen/COPYING.MINPACK
    - externals/Eigen/COPYING.README
    - externals/Eigen/COPYING.MPL2
    - externals/Eigen/COPYING.BSD
    - externals/Eigen/COPYING.APACHE
    - externals/Eigen/COPYING.GPL
    - externals/Eigen/COPYING.LGPL
    - externals/Eigen/bench/btl/COPYING
    - externals/Catch/LICENSE.txt

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
```
