### ISSUE TITLE
Add `pm-remez`

### ISSUE THREAD

**Issue by dhirschfeld** [energy-quants/quantdev#53]
* https://github.com/maia-sdr/pm-remez/

**Comment by dhirschfeld** [comment]
```yaml
{% set name = "pm-remez" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pm_remez-{{ version }}.tar.gz
  sha256: 10e6fa44b0d85782739ef501514ad8530d787c4587d22f2cd303195b90675946

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - pm_remez
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://maia-sdr.org/
  summary: Parks-McClellan Remez FIR design algorithm
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
```
